name: Question
description: Ask a question about using or deploying the bot
title: '[Question]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: |
        Have a question? Please check the documentation first:
        - [README.md](https://github.com/ningod/DooMandDastardlies/blob/main/README.md)
        - [SUPPORT.md](https://github.com/ningod/DooMandDastardlies/blob/main/SUPPORT.md)
        - [CONTRIBUTING.md](https://github.com/ningod/DooMandDastardlies/blob/main/CONTRIBUTING.md)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (what you're trying to accomplish, what you've tried)
      placeholder: I'm trying to deploy the bot to...
    validations:
      required: false

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
